# Site settings
author: Brittney 
title: My Coding Journey
header-img: img/home-bg.png
email: brittneyramirez79@gmail.com
copyright_name: Brittney 
description: > # this means to ignore newlines until "baseurl:"
  Learning the languages
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ramirezb45

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
